name: crisp_notation_example
description: Demo app for the crisp_notation music notation library.
publish_to: none
version: 0.1.0

environment:
  sdk: ^3.5.0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  crisp_notation:
    path: ../
  audioplayers: ^5.2.1
  provider: ^6.1.2
  file_picker: ^8.0.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
